# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest
 
    strategy:
      # Node versions list
      matrix:
        node-version: [14.x]
   

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: make install
    - run: make lint
    - name: Test & publish code coverage
      # Publish code coverage on Code Climate
      # https://github.com/paambaati/codeclimate-action
      uses: paambaati/codeclimate-action@v2.7.4
        # Add Code Climate secret key
      env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
      with:
          coverageCommand: make test-coverage
          debug: true
